apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: ticketify
build:
  artifacts:
  - image: bineetnaidu/ticketify-auth
    context: auth
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: 'src/**/*.ts'
          dest: .
  - image: bineetnaidu/ticketify-client
    context: client
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: '**/*.js'
          dest: .
deploy:
  kubectl:
    manifests:
    - k8s/auth-depl.yaml
    - k8s/auth-mongo-depl.yaml
    - k8s/ingress-srv.yaml
