apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: ticketify
build:
  artifacts:
  - image: bineetnaidu/ticketify-auth
    context: auth
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: 'src/**/*.ts'
          dest: .
deploy:
  kubectl:
    manifests:
    - k8s/*
