apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
    spec:
      containers:
      - name: tickets
        image: bineetnaidu/ticketify-tickets
        env:
          - name: NATS_URL
            value: http://nats-srv:4222
          - name: NATS_CLUSTER_ID
            value: ticketify
          - name: NATS_CLIENT_ID
            valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          - name: MONGO_URI
            value: 'mongodb://tickets-mongo-srv:27017/tickets'
          - name: JWT_KEY
            valueFrom:
              secretKeyRef:
                name: jwt-secret
                key: JWT_KEY
        resources:
          limits:
            memory: "125Mi"
            cpu: "150m"
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-srv
spec:
  selector:
    app: tickets
  ports:
  - name: tickets
    protocol: TCP
    port: 3000
    targetPort: 3000
